### PR TITLE
optionally match a ':' after username to ambush

### PR DESCRIPTION
**Pull request by awaxa**
because I can never remember to type it

### CODE REVIEW

**Comment by jjasghar** [comment]
Interesting idea. God knows i forget it myself :cry: 

Hopefully someone else'll :+1: it

**Comment by augieschwer** [comment]
Except I think the regex is too greedy and you won't always be able to match the user if you have say a "John S" and a "John B" -- it won't know where the user name ends and the message begins.

**Comment by jjasghar** [comment]
@augieschwer great point, @awaxa can you fix it so there is a way that it isnt so greedy? I'm not sure what the best way is.

**Comment by awaxa** [comment]
I didn't consider that spaces might be valid characters for usernames.  If the purpose of the colon is to clearly separate the username from the ambush message so that this script is compatible with usernames that include spaces, I at least now understand why it is necessary.

My desire to improve the usability of this script leads me to wonder if we could modify the capture group to be more precise.  This may be possible if we had strict criteria, but I don't think it would be worth the effort of creating and maintaining a regular expression to match any possible username for every hubot adapter.  Even if we were to decide that usernames with spaces aren't worth maintaining compatibility for, it would be a breaking change for existing users.

Thanks for entertaining my idea!

**Pull request closed without merging**
